Move BLE data to RAM DLT in deep sleep mode
telink-semi/zephyr pull request #166
Opened 2023-10-10 14:50 UTC by serhiiSalamakha

http://192.168.48.49:8080/browse/MATTER-393

2023-10-10 14:51 UTC, andriy-bilynskyy commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hal_telink | https://github.com/telink-semi/hal_telink/commit/6c4c9a1e2eab97017eead9e45b2f412417fc4959 | https://github.com/telink-semi/hal_telink/commit/a116ad41d9ea9b830d4d38066e3f5022131f1066 (develop) | [telink-semi/hal_telink@6c4c9a1e..a116ad41](https://github.com/telink-semi/hal_telink/compare/6c4c9a1e2eab97017eead9e45b2f412417fc4959..a116ad41d9ea9b830d4d38066e3f5022131f1066) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2023-10-11 08:25 UTC, andriy-bilynskyy requested changes

2023-10-11 08:25 UTC, andriy-bilynskyy commented on soc/riscv/riscv-privilege/telink_b9x/Kconfig.defconfig.series
> +	default 10240
Lets add this change to Matter. Here we set just minimal to avoid the situation when there is malloc() in project but config is not set. As resul we have an issue which is difficult to catch.

2023-10-11 08:31 UTC, andriy-bilynskyy commented
We need this relocation only for matter project to feet memory size.
So my proposition is to add some special config like
CONFIG_MATTER_RETENTION_LAYOUT by default set to "n".
From matter project enable this config and do all changes under this config.
BTW: now BT is incompatible with retention so it's good to disable this mode under BT enabling in HAL.

2023-10-11 10:52 UTC, serhiiSalamakha commented on soc/riscv/riscv-privilege/telink_b9x/Kconfig.defconfig.series
> +	default 10240
Changed

2023-10-11 11:19 UTC, andriy-bilynskyy commented
in file soc/riscv/riscv-privilege/telink_b9x/Kconfig.soc add
config TELINK_B9x_MATTER_RETENTION_LAYOUT
	bool "Support matter retention layout"
	default n
	depends on SOC_SERIES_RISCV_TELINK_B9X
	help
		...

2023-10-11 11:20 UTC, andriy-bilynskyy requested changes

2023-10-11 11:20 UTC, andriy-bilynskyy commented on soc/riscv/riscv-privilege/telink_b9x/matter_retention.ld
> +	*(.ram_dlm)
if hal changes are applied we don't need this line

2023-10-11 11:20 UTC, andriy-bilynskyy commented on soc/riscv/riscv-privilege/telink_b9x/CMakeLists.txt
> +if(CONFIG_BOARD_TLSR9518ADK80D_RETENTION OR CONFIG_BOARD_TLSR9528A_RETENTION)
if(TELINK_B9x_MATTER_RETENTION_LAYOUT)

2023-10-11 11:20 UTC, andriy-bilynskyy commented on soc/riscv/riscv-privilege/telink_b9x/start.S
> +#if defined(CONFIG_BOARD_TLSR9518ADK80D_RETENTION) || defined(CONFIG_BOARD_TLSR9528A_RETENTION)
if(TELINK_B9x_MATTER_RETENTION_LAYOUT)

2023-10-11 11:20 UTC, andriy-bilynskyy commented on soc/riscv/riscv-privilege/telink_b9x/start.S
> +#endif /* CONFIG_BOARD_TLSR9518ADK80D_RETENTION || CONFIG_BOARD_TLSR9528A_RETENTION */
#endif /* TELINK_B9x_MATTER_RETENTION_LAYOUT */

2023-10-11 14:02 UTC, andriy-bilynskyy approved these changes

2023-10-11 14:17 UTC, merged