soc: riscv: riscv-privilege: telink: Added Telink b92 soc PMP support
telink-semi/zephyr pull request #180
Opened 2023-12-11 15:45 UTC by mishadesh

Added the generic RISCV PMP support for B92 SoC series.

2023-12-13 08:00 UTC, andriy-bilynskyy commented
Can we create Telink config option for enabling memory protection feature?
Disable it for default (for now) and selects all features you provides.
In tht case it's safe entry point for memory protection implementation.

2023-12-13 08:49 UTC, mishadesh commented
> Can we create Telink config option for enabling memory protection feature? Disable it for default (for now) and selects all features you provides. In tht case it's safe entry point for memory protection implementation.

Yes, we can. But the purpose of it is not clear. This is just a description of CPU architecture. So we are not enabling the implementation of user space or memory protection.
Also the ROM size and RAM size is not changing in case if this option is enabled. 

The SiFive vendor just adds this option to his own core description.

So I think for development process we may go the way you suggested, but after we finish, we need to prepare our code in common way.

2023-12-15 08:41 UTC, andriy-bilynskyy requested changes

2023-12-15 08:41 UTC, andriy-bilynskyy commented on soc/riscv/riscv-privilege/telink_b9x/Kconfig.soc
> +	default n
By default option is no. Seems like this line is not required.

2023-12-15 08:41 UTC, andriy-bilynskyy commented on soc/riscv/riscv-privilege/telink_b9x/Kconfig.soc
> +config PMP_POWER_OF_TWO_ALIGNMENT
This option is no by default?

2023-12-15 08:41 UTC, andriy-bilynskyy commented on soc/riscv/riscv-privilege/telink_b9x/Kconfig.soc
> +	int
We are changing just value.

2023-12-18 08:43 UTC, andriy-bilynskyy requested changes

2023-12-18 08:43 UTC, andriy-bilynskyy commented on soc/riscv/riscv-privilege/telink_b9x/Kconfig.soc
> +config PMP_POWER_OF_TWO_ALIGNMENT
Why do we still need this line. Now seems it chhanges nothing.

2023-12-18 09:18 UTC, andriy-bilynskyy requested changes

2023-12-18 09:18 UTC, andriy-bilynskyy commented on soc/riscv/riscv-privilege/telink_b9x/Kconfig.soc
> +	depends on RISCV_PMP
```
if RISCV_PMP

config PMP_SLOTS
	int "Number of PMP slots"
	default 8
	help
	  This is the number of PMP entries implemented by the hardware.
	  Typical values are 8 or 16.
```
The dependency is already introduced. We just changing default
See soc/riscv/riscv-privilege/virt/Kconfig.defconfig.series

2023-12-18 09:36 UTC, andriy-bilynskyy requested changes

2023-12-18 09:36 UTC, andriy-bilynskyy commented on soc/riscv/riscv-privilege/telink_b9x/Kconfig.soc
> +	select RISCV_PMP
depends on SOC_RISCV_TELINK_B92
help ...

2023-12-18 10:17 UTC, andriy-bilynskyy approved these changes

2023-12-18 10:17 UTC, merged