driver: usb: Add USB driver for the TLSR9 series SoCs
telink-semi/zephyr pull request #21
Opened 2022-09-22 11:02 UTC by interfer

Co-authored-by: Dmytro Huz <diman1436@gmail.com>

Signed-off-by: Xiaohua Qiao <xiaohua.qiao@telink-semi.com>

2022-09-27 13:48 UTC, andriy-bilynskyy commented
Please finalyze PR. Set West revision and fix ompliance Checks

2022-09-27 13:55 UTC, andriy-bilynskyy requested changes

2022-09-27 13:55 UTC, andriy-bilynskyy commented on drivers/usb/device/Kconfig
> +config USB_TELINK_B91
Not sure we are able to change this file. See how other vendors solve it. I think we should create new one for our platform and just include it into common one.

2022-09-27 13:55 UTC, andriy-bilynskyy commented on samples/subsys/usb/hid-mouse/src/main.c
>  	int ret;
This file is common for all vendors that's not possible to change. We should use overlays for our board

2022-09-27 13:55 UTC, andriy-bilynskyy commented on include/zephyr/usb/usb_device.h
> +#define USB_MAX_CTRL_MPS	8   /**< maximum packet size (MPS) for EP 0 */
No changes in this file

2022-09-28 09:57 UTC, damien0x0023 commented on drivers/usb/device/Kconfig
> +config USB_TELINK_B91
I see other vendors add their specific configurations in this Kconfig, such as USB_NRFX, and USB_DC_STM32. I recommend we can change USB_TELINK_B91 to something similar.

2022-09-28 10:04 UTC, damien0x0023 commented on include/zephyr/usb/usb_device.h
> +#define USB_MAX_CTRL_MPS	8   /**< maximum packet size (MPS) for EP 0 */
Agreed. We may mention this change and explain the reason in our README or other docs so that anyone can modify it by themselves.

2022-09-28 10:05 UTC, damien0x0023 commented on samples/subsys/usb/hid-mouse/src/main.c
>  	int ret;
The modification in the sample source code will affect other vendors' implementation. I'm afraid we cannot use overlays to override the source file here.

2022-09-28 12:36 UTC, damien0x0023 commented on samples/subsys/usb/hid-mouse/src/main.c
>  	int ret;
Maybe we can generate a file called "telink-hid-mouse.patch" and send them to customers. They then can use "git apply telink-hid-mouse.patch" to achieve the purpose of the overlay on their side.

2022-10-11 10:45 UTC, interfer commented on samples/subsys/usb/hid-mouse/src/main.c
>  	int ret;
Did a revert as we discussed, in order not to change common sample files

2022-10-11 10:49 UTC, interfer commented on drivers/usb/device/Kconfig
> +config USB_TELINK_B91
Should any changes here be applied? Or leave it as is?

2022-10-11 10:49 UTC, interfer commented
> Please finalyze PR. Set West revision and fix ompliance Checks

Done, waiting for the approve

2022-10-11 10:57 UTC, liucoldstar approved these changes

2022-10-11 11:03 UTC, liucoldstar commented on drivers/usb/device/Kconfig
> +config USB_TELINK_B91
I guess these changes seem quite necessary. Xiaohua made copied of similar config items created by Nordic.

2022-10-11 14:00 UTC, andriy-bilynskyy commented
Compliance Checks / Run compliance checks on patch series (PR) (pull_request)  failed. Plese fix it

2022-10-17 01:59 UTC, andy-liu-telink approved these changes

2022-10-18 06:42 UTC, andriy-bilynskyy approved these changes
Please merge it be carefull with squashing commit message. As for me it's better to do it localy and force push to one commit.

2022-10-18 11:19 UTC, merged