Add pin controller driver for W91
telink-semi/zephyr pull request #223
Opened 2024-02-29 16:46 UTC by serhiiSalamakha

http://192.168.48.49:8080/browse/ZEPHYR-428

2024-03-01 10:06 UTC, andriy-bilynskyy requested changes

2024-03-01 10:06 UTC, andriy-bilynskyy commented on boards/riscv/tlsr9118bdk40d/tlsr9118bdk40d-common.dtsi
> +		zephyr,console = &uart1;
we have special debug backend on uart0. Why do we relocate this?

2024-03-01 10:06 UTC, andriy-bilynskyy commented on boards/riscv/tlsr9118bdk40d/tlsr9118bdk40d-pinctrl.dtsi
> +	/* UART0: TX(P22), RX(P21), RTS(P20), CTS(P19) */
uart0 is reserved for debugging. we shouldn't add it here

2024-03-01 10:06 UTC, andriy-bilynskyy commented on boards/riscv/tlsr9118bdk40d/tlsr9118bdk40d-pinctrl.dtsi
> +
uart1 is used for debug in core N22...

2024-03-01 10:06 UTC, andriy-bilynskyy commented on boards/riscv/tlsr9118bdk40d/tlsr9118bdk40d_defconfig
> +CONFIG_SERIAL=y
We are making conflicts with our debug backend

2024-03-01 10:06 UTC, andriy-bilynskyy commented on drivers/pinctrl/pinctrl_w91.c
> +SYS_INIT(pinctrl_w91_pin_map_set, POST_KERNEL, CONFIG_PINCTRL_TELINK_W91_PIN_MAP_SET_PRIORITY);
Seems like driver workaround not a driver.
When some device with pinctrl functionality is initing it configures its pins...

2024-03-01 14:16 UTC, serhiiSalamakha commented on boards/riscv/tlsr9118bdk40d/tlsr9118bdk40d-common.dtsi
> +		zephyr,console = &uart1;
Updated

2024-03-01 14:16 UTC, serhiiSalamakha commented on boards/riscv/tlsr9118bdk40d/tlsr9118bdk40d-pinctrl.dtsi
> +	/* UART0: TX(P22), RX(P21), RTS(P20), CTS(P19) */
Updated

2024-03-01 14:16 UTC, serhiiSalamakha commented on boards/riscv/tlsr9118bdk40d/tlsr9118bdk40d-pinctrl.dtsi
> +
Updated

2024-03-01 14:18 UTC, serhiiSalamakha commented on boards/riscv/tlsr9118bdk40d/tlsr9118bdk40d_defconfig
> +CONFIG_SERIAL=y
Updated

2024-03-01 14:18 UTC, serhiiSalamakha commented on drivers/pinctrl/pinctrl_w91.c
> +SYS_INIT(pinctrl_w91_pin_map_set, POST_KERNEL, CONFIG_PINCTRL_TELINK_W91_PIN_MAP_SET_PRIORITY);
Updated

2024-03-04 08:41 UTC, andriy-bilynskyy approved these changes

2024-03-04 08:41 UTC, merged