drivers: hwinfo: spi-flash-id: add hwinfo driver
telink-semi/zephyr pull request #259
Opened 2024-05-29 20:17 UTC by BorysNykytiuk

- Added hwinfo driver for the w91 board
 - Extend soc_flash_w91 API driver

   Signed-off-by: Borys Nykytiuk <borys.nykytiuk@gmail.com>

2024-05-30 07:37 UTC, andriy-bilynskyy commented
Plese fix CI

2024-05-30 07:38 UTC, andriy-bilynskyy commented
@serhiiSalamakha could you review this PR?

2024-05-30 07:44 UTC, andriy-bilynskyy requested changes

2024-05-30 07:44 UTC, andriy-bilynskyy commented on drivers/flash/soc_flash_w91.c
> +    ipc_based_driver_init(&ipc_flash_id);
Why do we have 2x structures?

2024-05-30 07:44 UTC, andriy-bilynskyy commented on drivers/flash/soc_flash_w91.c
> +#define IPC_FLASH_HWINFO_INSTANCE (uint8_t)0
This shouldn't be hardcoded

2024-05-30 07:45 UTC, andriy-bilynskyy commented
As for me there is a collision in SPI flash acess by this changes.
HW info and flash should use same mutex to avoid it.

2024-06-03 10:03 UTC, andriy-bilynskyy approved these changes

2024-06-03 10:20 UTC, BorysNykytiuk commented on drivers/flash/soc_flash_w91.c
> +    ipc_based_driver_init(&ipc_flash_id);
fixed

2024-06-03 10:21 UTC, BorysNykytiuk commented on drivers/flash/soc_flash_w91.c
> +#define IPC_FLASH_HWINFO_INSTANCE (uint8_t)0
Fsxed

2024-06-04 19:29 UTC, closed without merging