telink: b92: update hal commit.
telink-semi/zephyr pull request #328
Opened 2024-09-02 09:49 UTC by haiwentelink

- update hal commit for hal .

2024-09-02 09:50 UTC, andriy-bilynskyy commented
The following west manifest projects have been modified in this Pull Request:

| Name | Old Revision | New Revision | Diff |
| ---- | ------------ | ------------ |------|
| hal_telink | https://github.com/telink-semi/hal_telink/commit/f3eb7a8bc1712e2f9308c58276c875de1c7bde52 | https://github.com/telink-semi/hal_telink/pull/101 | [telink-semi/hal_telink#101/files](https://github.com/telink-semi/hal_telink/pull/101/files) |

*Note: This message is automatically posted and updated by the Manifest GitHub Action.*

2024-09-02 15:20 UTC, andriy-bilynskyy requested changes

2024-09-02 15:20 UTC, andriy-bilynskyy commented on west.yml
> +      revision: pull/101/head
Please update revision (hal already merged)

2024-09-04 01:55 UTC, haiwentelink commented
@andriy-bilynskyy  CI have already passed , and commit id have already update .

2024-09-04 02:16 UTC, andy-liu-telink approved these changes
Approve

2024-09-04 03:55 UTC, andriy-bilynskyy approved these changes

2024-09-04 03:56 UTC, merged