telink: Factory Data sample
telink-semi/zephyr pull request #435
Opened 2024-12-31 15:36 UTC by interfer

Read, parse and print Matter Factory Data Partition from simple Zephyr sample.
You should have factory_partition present/flashed and run the sample after.

2024-12-31 15:57 UTC, andriy-bilynskyy requested changes

2024-12-31 15:57 UTC, andriy-bilynskyy commented on samples/boards/tlsr9x/factorydata/src/factory_data_parser.c
> +__attribute__((section(
What is the reason to keep RAM image?
As I understand it's enough to declare structure. And make const pointer to flash area.

2025-01-02 10:33 UTC, interfer commented on samples/boards/tlsr9x/factorydata/src/factory_data_parser.c
> +__attribute__((section(
@andriy-bilynskyy Refactored now

2025-01-02 19:02 UTC, andriy-bilynskyy requested changes

2025-01-02 19:02 UTC, andriy-bilynskyy commented on samples/boards/tlsr9x/factorydata/src/factory_data_parser.h
> +#include <zephyr/storage/flash_map.h>
Why this headers are here?

2025-01-02 19:02 UTC, andriy-bilynskyy commented on samples/boards/tlsr9x/factorydata/src/factory_data_parser.h
> +#include <zephyr/kernel.h>
Same...

2025-01-02 19:02 UTC, andriy-bilynskyy commented on samples/boards/tlsr9x/factorydata/src/factory_data_parser.c
> +		if (strncmp("version", (const char *)currentString.value, currentString.len) == 0) {
memcmp

2025-01-02 19:02 UTC, andriy-bilynskyy commented on samples/boards/tlsr9x/factorydata/prj.conf
> +CONFIG_ZCBOR=y
seems CONFIG_LOG?

2025-01-02 19:02 UTC, andriy-bilynskyy commented on samples/boards/tlsr9x/factorydata/src/main.c
> +#include <zephyr/logging/log.h>
or why log is here?

2025-01-02 19:03 UTC, andriy-bilynskyy commented
Sqush your commits in PR

2025-01-02 19:07 UTC, andriy-bilynskyy commented on samples/boards/tlsr9x/factorydata/src/factory_data_parser.h
> +struct FactoryDataString {
struct zcbor_string???

2025-01-02 19:19 UTC, andriy-bilynskyy commented
Please add ci for target you tested

2025-01-03 10:28 UTC, andriy-bilynskyy approved these changes

2025-01-03 10:37 UTC, s07641069 approved these changes

2025-01-03 10:37 UTC, merged