Telink B92 GPIO driver adoption
telink-semi/zephyr pull request #78
Opened 2023-04-13 16:20 UTC by interfer

Refactored gpio_b91 API to become common driver for both B91 and B92 SoCs: gpio_b9x

2023-04-13 18:09 UTC, s07641069 requested changes

2023-04-13 18:09 UTC, s07641069 commented on samples/basic/blinky/src/main.c
Try to revert and test original main.c file from develop branch.
k_msleep function should work

2023-04-13 18:09 UTC, s07641069 commented on dts/bindings/gpio/telink,b9x-gpio.yaml
> +# Copyright (c) 2023, Telink Semiconductor
use "2021-2023" instead of "2023"
set single "2023" only for new files

2023-04-13 18:09 UTC, s07641069 commented on drivers/gpio/Kconfig.b9x
> +# Copyright (c) 2023 Telink Semiconductor
use "2021-2023" instead of "2023"
set single "2023" only for new files

2023-04-13 18:09 UTC, s07641069 commented on boards/riscv/tlsr9528a/tlsr9528a-pinctrl.dtsi
> + * Copyright (c) 2022 Telink Semiconductor
2023

2023-04-13 18:09 UTC, s07641069 commented on boards/riscv/tlsr9528a/tlsr9528a-pinctrl.dtsi
> +#include <zephyr/dt-bindings/pinctrl/b91-pinctrl.h>
if this is common file please rename file into b9x-* and fix path here and for b91 dtsi

2023-04-13 18:09 UTC, s07641069 commented on boards/riscv/tlsr9528a/tlsr9528a-pinctrl.dtsi
> +		pinmux = <B91_PINMUX_SET(B91_PORT_B, B91_PIN_2, B91_FUNC_C)>;
Fix B91 into B9x for B91_PINMUX_SET, B91_PORT_D, B91_PIN_1, B91_FUNC_B and all places where B91 mentioned, may impact partly pinmux driver. Or do this in next task adopt and fix pinmux driver.

2023-04-13 18:09 UTC, s07641069 commented on boards/riscv/tlsr9528a/tlsr9528a.dts
Here are two compliance checks errors, please fix.

2023-04-13 18:09 UTC, s07641069 commented on drivers/gpio/gpio_b9x.c
> + * Copyright (c) 2023 Telink Semiconductor
use 2021-2023

2023-04-13 18:09 UTC, s07641069 commented on drivers/gpio/gpio_b9x.c
one compliance check error in this file, please fix

2023-04-13 18:14 UTC, s07641069 commented on boards/riscv/tlsr9528a/tlsr9528a-pinctrl.dtsi
> +#include <zephyr/dt-bindings/pinctrl/b91-pinctrl.h>
Also change content of zephyr/dt-bindings/pinctrl/b91-pinctrl.h file in same way, replace B91 into B9x and after fix all related files for b91 doc

2023-04-14 13:57 UTC, interfer commented on boards/riscv/tlsr9528a/tlsr9528a-pinctrl.dtsi
> +#include <zephyr/dt-bindings/pinctrl/b91-pinctrl.h>
There's no access to SOC-macro (CONFIG_SOC_RISCV_TELINK_B91/92) in `b91-pinctrl.h` so moved definitions to separate B92 header file

2023-04-18 08:04 UTC, s07641069 commented on boards/riscv/tlsr9528a/tlsr9528a-pinctrl.dtsi
> +#include <zephyr/dt-bindings/pinctrl/b91-pinctrl.h>
Still b91-pinctrl.h instead of b92-pinctrl.h or b9x-pinctrl.h

2023-04-18 08:05 UTC, s07641069 commented on boards/riscv/tlsr9528a/tlsr9528a-pinctrl.dtsi
> + * Copyright (c) 2022 Telink Semiconductor
no changes yet

2023-04-18 08:06 UTC, s07641069 commented on drivers/gpio/Kconfig.b9x
> +# Copyright (c) 2023 Telink Semiconductor
no changes yet

2023-04-19 07:16 UTC, s07641069 requested changes

2023-04-19 07:16 UTC, s07641069 commented on drivers/pinctrl/pinctrl_b9x.c
Use 2022-2023 in header

2023-04-19 07:16 UTC, s07641069 commented on dts/bindings/pinctrl/telink,b9x-pinctrl.yaml
>  # SPDX-License-Identifier: Apache-2.0
use 2022-2023 in header

2023-04-19 07:16 UTC, s07641069 commented on dts/bindings/pinctrl/telink,b9x-pinctrl.yaml
>            /* configure PB2 as B91_FUNC_C */
Still see B91 in 4 places, can we change into B9x?

2023-04-19 07:16 UTC, s07641069 commented on include/zephyr/dt-bindings/pinctrl/b91-pinctrl.h
>  #ifndef ZEPHYR_B91_PINCTRL_COMMON_H_
use 2021-2023

2023-04-19 07:16 UTC, s07641069 commented on include/zephyr/dt-bindings/pinctrl/b91-pinctrl.h
> +#define B92_FUNC_MSK     0x3
Why here B92 ? should be B9x or B91

2023-04-19 07:28 UTC, s07641069 approved these changes

2023-04-25 06:59 UTC, closed without merging

2023-04-25 07:00 UTC, serhiiSalamakha commented
Added in https://github.com/telink-semi/zephyr/pull/84